Algoritmo "ContarAte10ComPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/11/2023
Var
// Seção de Declarações das variáveis 
C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para C <- 1 ate 10 passo 1 faca
   Escreva(C)
   FimPara


Fimalgoritmo