Algoritmo "VERDADEIRO OU FALSO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/11/2023
Var
// Seção de Declarações das variáveis 
A, B, C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
A <- 1
B <- 2
C <- 3
Escreva (A<>B)


Fimalgoritmo